theme: light
jwt_secret: ${AUTHELIA_JWT_SECRET}
default_redirection_url: https://${DOMAIN_NAME}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: ${DOMAIN_NAME}
      policy: one_factor
    - domain: "grafana.${DOMAIN_NAME}"
      policy: one_factor

session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  expiration: 1h
  inactivity: 5m
  domain: ${DOMAIN_NAME}

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt
